// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "wwdc26",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "wwdc26",
            targets: ["AppModule"],
            bundleIdentifier: "com.sofia.wwdc26",
            teamIdentifier: "2U7Y6S5549",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.teal),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft,
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
//            resources: [
//                .process("Resources")
//            ]
        )
    ],
    swiftLanguageModes: [.version("6")]
)
